# Open PR -> deploy to Maven Central Staging
name: Deploy to Maven Central Staging

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  deploy-mavencentral:
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/actions/gradle-cache
      - name: Set Staging version
        run: |
          sed -i "" -E "s/^kfswatch = \"(.*)\"$/kfswatch = \"\\1-pr${{ github.event.pull_request.number }}.${{ github.run_number }}.${{ github.run_attempt }}\"/g" gradle/libs.versions.toml
          grep "^kfswatch" gradle/libs.versions.toml
      - name: Deploy to Maven Central
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME_TOKEN }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD_TOKEN }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
        run: |
          ./gradlew publishToSonatype closeSonatypeStagingRepository
